---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springboot-app
  namespace: default
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: "kiranpkdocker/MyYoutube-app:latest"
        ports:
          - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: default
spec:
  selector:
    app: springboot-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8082
    port: 80
               
