name: Terraform Workflow

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # or your desired version

      - name: Terraform Init
        working-directory: ./EKS_Terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./EKS_Terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./EKS_Terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./EKS_Terraform
        run: terraform apply -auto-approve
